// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnsijzpulgvmdvqzfjjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuc2lqenB1bGd2bWR2cXpmampxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTA1MDksImV4cCI6MjA2MDk4NjUwOX0.yXV4ZtUcZXSdubFKrV1sMPGJmAljetR8ZXlq8U2hzHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);